[package]
name = "cs492-concur-homework"
version = "0.1.0"
authors = ["Jeehoon Kang <jeehoon.kang@kaist.ac.kr>"]
edition = "2018"

[dependencies]
arr_macro = "0.1.3"
crossbeam-channel = "0.4.3"
crossbeam-epoch = "0.8.2"
crossbeam-utils = "0.7.2"
ctrlc = "3.1.6"
either = "1.6.0"
itertools = "0.9.0"
lazy_static = "1.4.0"
# TODO: use relative path so that students don't need to manually update
lock = { git = "https://github.com/kaist-cp/cs492-concur" }
rand = "0.7.3"
regex = "1.3.9"
static_assertions = "1.1.0"
